export interface PromptTemplate {
  id: string;
  title: string;
  category: string;
  categoryEmoji: string;
  prompt: string;
  score: number;
  explanation: string;
}

export const CATEGORIES = [
  { key: 'all', label: 'All', emoji: '📋' },
  { key: 'content', label: 'Content Writing', emoji: '✍️' },
  { key: 'coding', label: 'Coding', emoji: '💻' },
  { key: 'business', label: 'Business', emoji: '📊' },
  { key: 'education', label: 'Education', emoji: '🎓' },
  { key: 'creative', label: 'Creative', emoji: '🎨' },
  { key: 'marketing', label: 'Marketing', emoji: '📢' },
  { key: 'system', label: 'System Prompts', emoji: '⚙️' },
];

export const FREE_TEMPLATES: PromptTemplate[] = [
  {
    id: '1',
    title: 'SEO Blog Post Writer',
    category: 'content',
    categoryEmoji: '✍️',
    prompt: 'You are an expert SEO content strategist with 10+ years of experience writing for high-authority websites. Write a 1,500-word blog post about [TOPIC] optimized for the keyword "[KEYWORD]".\n\nStructure:\n1. Engaging hook (2-3 sentences)\n2. Brief overview paragraph\n3. 5-7 H2 sections with actionable insights\n4. Each section: 150-200 words with examples\n5. Conclusion with clear CTA\n\nTone: Professional but conversational. Write at an 8th-grade reading level.\nFormat: Markdown with H2 headings, bold key terms, and bullet points.\nConstraints: No fluff. Every sentence must add value. Include 2-3 internal linking opportunities marked as [INTERNAL LINK: topic].',
    score: 94,
    explanation: 'Uses role assignment, structured sections, specific word counts, tone guidance, format specs, and constraints. Hits all 8 dimensions of the Efficient Prompt Blueprint.',
  },
  {
    id: '2',
    title: 'Code Review Assistant',
    category: 'coding',
    categoryEmoji: '💻',
    prompt: 'You are a senior software engineer conducting a thorough code review. Analyze the following code for:\n\n1. **Bugs & Logic Errors**: Identify any bugs, edge cases, or logical flaws\n2. **Performance**: Flag any performance bottlenecks or inefficient patterns\n3. **Security**: Check for security vulnerabilities (XSS, injection, auth issues)\n4. **Readability**: Assess naming, structure, and documentation\n5. **Best Practices**: Compare against industry standards and design patterns\n\nFor each issue found:\n- Severity: 🔴 Critical | 🟡 Warning | 🔵 Info\n- Line/section reference\n- What\'s wrong and why\n- Suggested fix with code example\n\nCode to review:\n```\n[PASTE CODE HERE]\n```\n\nEnd with an overall quality score (1-10) and top 3 priority fixes.',
    score: 92,
    explanation: 'Assigns expert role, provides structured review categories, defines severity levels, and requests actionable fixes with code examples.',
  },
  {
    id: '3',
    title: 'Business Strategy Analyzer',
    category: 'business',
    categoryEmoji: '📊',
    prompt: 'You are a McKinsey-level management consultant with expertise in [INDUSTRY]. Analyze the following business situation and provide strategic recommendations.\n\nContext: [DESCRIBE SITUATION]\n\nDeliver your analysis in this structure:\n1. **Situation Assessment** (3-4 key observations)\n2. **Root Cause Analysis** (using the "5 Whys" framework)\n3. **Strategic Options** (3 options with pros/cons/risks for each)\n4. **Recommended Action Plan** (prioritized, with timelines)\n5. **Key Metrics to Track** (5-7 KPIs)\n6. **Risk Mitigation** (top 3 risks and contingency plans)\n\nTone: Executive-level, data-driven, decisive.\nConstraints: No generic advice. Every recommendation must be specific and actionable. Include estimated impact where possible.',
    score: 91,
    explanation: 'Uses prestigious role anchoring, structured frameworks, specific deliverable format, and constraints against vagueness.',
  },
  {
    id: '4',
    title: 'Lesson Plan Generator',
    category: 'education',
    categoryEmoji: '🎓',
    prompt: 'You are an award-winning [SUBJECT] teacher with 15 years of experience teaching [GRADE LEVEL] students. Create a detailed 45-minute lesson plan on [TOPIC].\n\nInclude:\n1. **Learning Objectives** (3 measurable outcomes using Bloom\'s taxonomy)\n2. **Materials Needed** (specific list)\n3. **Warm-Up Activity** (5 min) — engage prior knowledge\n4. **Direct Instruction** (10 min) — key concepts with analogies\n5. **Guided Practice** (15 min) — interactive activity\n6. **Independent Practice** (10 min) — student work\n7. **Closure** (5 min) — summary and exit ticket\n8. **Differentiation** — modifications for advanced, on-level, and struggling learners\n9. **Assessment** — how to measure understanding\n\nTone: Engaging and age-appropriate.\nFormat: Use clear headers, time stamps, and teacher scripts where helpful.',
    score: 93,
    explanation: 'Detailed role with experience level, structured lesson flow with time allocations, differentiation requirements, and specific pedagogical frameworks.',
  },
  {
    id: '5',
    title: 'Creative Story Starter',
    category: 'creative',
    categoryEmoji: '🎨',
    prompt: 'You are a bestselling fiction author known for [GENRE] novels. Write the opening chapter (1,000-1,200 words) of a story with these parameters:\n\n**Setting:** [TIME PERIOD], [LOCATION]\n**Protagonist:** [NAME], [AGE], [KEY TRAIT], [SECRET DESIRE]\n**Opening Hook:** Start with [ACTION/DIALOGUE/MYSTERY] that immediately creates tension\n**Tone:** [DARK/WHIMSICAL/GRITTY/LITERARY]\n**POV:** [FIRST/THIRD LIMITED/OMNISCIENT]\n\nWriting requirements:\n- Show, don\'t tell — use sensory details (sight, sound, smell)\n- Introduce the central conflict within the first 500 words\n- End the chapter on a cliffhanger or unanswered question\n- Include at least one line of dialogue that reveals character\n- Avoid clichés and purple prose\n\nAfter the chapter, provide a 3-sentence outline of where the story goes next.',
    score: 90,
    explanation: 'Detailed creative parameters, specific writing craft requirements, structural expectations, and constraints against common pitfalls.',
  },
  {
    id: '6',
    title: 'Email Subject Line Generator',
    category: 'content',
    categoryEmoji: '✍️',
    prompt: 'You are an email marketing expert with a 35%+ average open rate. Generate 10 subject lines for an email about [TOPIC/OFFER] targeting [AUDIENCE].\n\nFor each subject line:\n- Character count (keep under 50 chars)\n- Psychological trigger used (curiosity, urgency, social proof, etc.)\n- Predicted open rate: Low / Medium / High\n\nMix of styles:\n- 3 curiosity-driven\n- 2 urgency/scarcity\n- 2 benefit-focused\n- 2 question-based\n- 1 controversial/bold\n\nConstraints: No spam trigger words (FREE, ACT NOW). No all-caps. No excessive punctuation.',
    score: 89,
    explanation: 'Specific deliverable count, categorized styles, measurable criteria, and spam-avoidance constraints.',
  },
  {
    id: '7',
    title: 'API Documentation Writer',
    category: 'coding',
    categoryEmoji: '💻',
    prompt: 'You are a senior technical writer specializing in API documentation. Create comprehensive documentation for the following API endpoint:\n\nEndpoint: [METHOD] [URL]\nPurpose: [DESCRIPTION]\n\nDocument using this structure:\n1. **Overview** — What this endpoint does and when to use it\n2. **Authentication** — Required auth method and headers\n3. **Request** — Parameters (path, query, body) with types and validation rules\n4. **Response** — Success and error responses with full JSON examples\n5. **Code Examples** — cURL, JavaScript (fetch), and Python (requests)\n6. **Rate Limits** — If applicable\n7. **Common Errors** — Table with error codes, causes, and fixes\n\nFormat: Use markdown with code blocks. Include realistic example values, not "string" or "123".\nConstraints: Assume the reader is a junior developer. Define all technical terms.',
    score: 91,
    explanation: 'Expert role, comprehensive documentation structure, multiple code examples, and audience-appropriate language level.',
  },
  {
    id: '8',
    title: 'Competitor Analysis Framework',
    category: 'business',
    categoryEmoji: '📊',
    prompt: 'You are a competitive intelligence analyst. Conduct a comprehensive competitor analysis for [MY COMPANY] against [COMPETITOR 1], [COMPETITOR 2], and [COMPETITOR 3] in the [INDUSTRY] market.\n\nAnalyze across these dimensions:\n1. **Product/Service Comparison** — Feature matrix with ✅/❌/⚡(partial)\n2. **Pricing Strategy** — Models, tiers, value perception\n3. **Market Positioning** — Brand messaging, target audience, USP\n4. **Strengths & Weaknesses** — SWOT for each competitor\n5. **Digital Presence** — Website, SEO, social media, content strategy\n6. **Customer Sentiment** — Based on common review themes\n7. **Strategic Recommendations** — 5 actions to differentiate and win\n\nFormat: Use tables where possible. Bold key insights.\nConstraints: Be objective. Support claims with reasoning. Flag assumptions clearly.',
    score: 90,
    explanation: 'Structured multi-dimensional analysis, visual format specifications, objectivity constraints, and actionable output.',
  },
  {
    id: '9',
    title: 'Interactive Quiz Creator',
    category: 'education',
    categoryEmoji: '🎓',
    prompt: 'You are an assessment design specialist. Create a 10-question quiz on [TOPIC] for [AUDIENCE/LEVEL].\n\nQuiz structure:\n- Questions 1-3: Easy (knowledge recall)\n- Questions 4-6: Medium (application)\n- Questions 7-9: Hard (analysis/synthesis)\n- Question 10: Challenge (creative problem-solving)\n\nFor each question provide:\n- The question\n- 4 multiple-choice options (A-D)\n- Correct answer with detailed explanation\n- Common misconception addressed\n- Difficulty tag: 🟢 Easy | 🟡 Medium | 🔴 Hard\n\nEnd with: Scoring guide and 3 recommended resources for further learning.\n\nConstraints: No trick questions. Options should be plausible. Avoid "all of the above" or "none of the above."',
    score: 88,
    explanation: 'Progressive difficulty, detailed answer requirements, misconception handling, and assessment best practices.',
  },
  {
    id: '10',
    title: 'Brand Voice Guidelines',
    category: 'creative',
    categoryEmoji: '🎨',
    prompt: 'You are a brand strategist who has built voice guidelines for Fortune 500 companies. Create a comprehensive brand voice guide for [BRAND NAME], a [TYPE OF COMPANY] targeting [AUDIENCE].\n\nInclude:\n1. **Brand Personality** — 5 key traits with descriptions\n2. **Voice Characteristics** — Tone spectrum (formal ←→ casual, serious ←→ playful, etc.)\n3. **Do\'s and Don\'ts** — 10 examples each\n4. **Word Bank** — 20 "power words" to use, 20 words to avoid\n5. **Sample Copy** — Write the same message in 3 contexts:\n   - Social media post\n   - Email to customer\n   - Error message in the app\n6. **Adaptation Guide** — How voice changes by channel and audience segment\n\nFormat: Use headers, tables, and examples. Make it a working reference document.\nConstraints: Ensure consistency across all examples. Voice must be distinctive, not generic.',
    score: 91,
    explanation: 'Comprehensive brand framework, practical examples across channels, specific deliverable counts, and actionable reference format.',
  },
  // More templates
  {
    id: '11',
    title: 'Product Description Writer',
    category: 'content',
    categoryEmoji: '✍️',
    prompt: 'You are a conversion-focused copywriter for e-commerce. Write a compelling product description for [PRODUCT NAME] — a [PRODUCT TYPE] priced at [PRICE].\n\nTarget customer: [DEMOGRAPHIC + PAIN POINTS]\n\nStructure:\n1. **Headline** (under 10 words, benefit-driven)\n2. **Hook** (1-2 sentences addressing the pain point)\n3. **Key Benefits** (5 bullet points, feature → benefit format)\n4. **Social Proof Line** (e.g., "Join 10,000+ happy customers")\n5. **Sensory Description** (what it looks/feels/sounds like)\n6. **CTA** (urgency-driven closing line)\n\nTone: Persuasive but honest. No hyperbole.\nSEO: Naturally include keywords: [KEYWORD 1], [KEYWORD 2]\nLength: 200-300 words total.',
    score: 92,
    explanation: 'Clear audience targeting, benefit-driven structure, SEO integration, and specific word count with format requirements.',
  },
  {
    id: '12',
    title: 'Debugging Assistant',
    category: 'coding',
    categoryEmoji: '💻',
    prompt: 'You are a senior developer and debugging specialist. Help me fix this bug.\n\n**Error message:** [PASTE ERROR]\n**Code causing the issue:**\n```\n[PASTE CODE]\n```\n**What I expected:** [EXPECTED BEHAVIOR]\n**What actually happens:** [ACTUAL BEHAVIOR]\n**What I\'ve already tried:** [ATTEMPTS]\n\nPlease:\n1. Explain WHY this error occurs (root cause)\n2. Provide the EXACT fix with corrected code\n3. Explain what the fix does and why it works\n4. Suggest how to prevent this type of bug in the future\n5. Flag any other potential issues in the code\n\nConstraints: Don\'t just fix it — help me understand it. Use simple analogies if the concept is complex.',
    score: 90,
    explanation: 'Structured bug report format, requests both fix and explanation, emphasizes learning, and prevents similar future issues.',
  },
  {
    id: '13',
    title: 'Meeting Agenda Builder',
    category: 'business',
    categoryEmoji: '📊',
    prompt: 'You are an executive assistant known for running efficient meetings. Create a structured agenda for a [DURATION]-minute [TYPE] meeting.\n\nMeeting purpose: [PURPOSE]\nAttendees: [ROLES/NAMES]\nKey decisions needed: [LIST]\n\nAgenda format:\n| Time | Topic | Owner | Goal | Duration |\n|------|-------|-------|------|----------|\n\nInclude:\n- 2-min opening (context + objectives)\n- Discussion items with time allocations\n- 5-min buffer for overflow\n- Action items capture section\n- 2-min closing (summary + next steps)\n\nAlso provide:\n- Pre-read materials list\n- 3 ground rules for the meeting\n- Post-meeting email template\n\nConstraints: Total time must equal [DURATION] minutes exactly. No agenda item longer than 15 minutes.',
    score: 89,
    explanation: 'Time-bound structure, role assignments, clear deliverables, and practical supporting materials.',
  },
  {
    id: '14',
    title: 'Explain Like I\'m Five',
    category: 'education',
    categoryEmoji: '🎓',
    prompt: 'You are a science communicator who makes complex topics accessible to anyone. Explain [COMPLEX TOPIC] in 3 levels of increasing complexity:\n\n**Level 1 — ELI5 (Explain Like I\'m 5):**\nUse a simple analogy from everyday life. Max 3 sentences.\n\n**Level 2 — High School:**\nUse proper terminology with definitions. Include a real-world example. 1 paragraph.\n\n**Level 3 — Expert:**\nTechnical explanation with nuance, caveats, and current debates in the field. 2-3 paragraphs.\n\nFor each level, include:\n- A memorable analogy or metaphor\n- One "mind-blowing" fact\n- A common misconception debunked\n\nTone: Enthusiastic but accurate. Like a great TED talk.\nConstraints: No jargon without definition. No oversimplification that leads to misconceptions.',
    score: 91,
    explanation: 'Progressive complexity levels, multiple explanation techniques, misconception handling, and accuracy constraints.',
  },
  {
    id: '15',
    title: 'Brainstorming Facilitator',
    category: 'creative',
    categoryEmoji: '🎨',
    prompt: 'You are a creative director leading a brainstorming session. Generate ideas for [CHALLENGE/OBJECTIVE].\n\nTarget audience: [WHO]\nConstraints: [BUDGET/TIME/TECH LIMITATIONS]\n\nGenerate ideas in 4 rounds:\n\n**Round 1 — Safe Bets (5 ideas):** Proven approaches with low risk\n**Round 2 — Creative Twists (5 ideas):** Unexpected angles on conventional approaches\n**Round 3 — Moonshots (5 ideas):** Bold, ambitious, "what if we could?" ideas\n**Round 4 — Wildcard (3 ideas):** Cross-industry inspiration, completely unconventional\n\nFor each idea:\n- One-line title\n- 2-3 sentence description\n- Estimated effort: Low / Medium / High\n- Potential impact: Low / Medium / High\n- Key risk or challenge\n\nEnd with: Top 3 recommended ideas with implementation steps.\n\nConstraints: No cliché ideas (e.g., "leverage social media"). Every idea must be specific and actionable.',
    score: 93,
    explanation: 'Structured ideation rounds with risk gradients, evaluation criteria per idea, and anti-cliché constraints.',
  },
  {
    id: '16',
    title: 'Social Media Thread Writer',
    category: 'content',
    categoryEmoji: '✍️',
    prompt: 'You are a viral content creator with 500K+ followers. Write a [PLATFORM] thread/post series about [TOPIC].\n\nThread structure (10 posts):\n1. Hook — Provocative opening stat or question (stop the scroll)\n2-8. Core content — One insight per post, building on each other\n9. Summary — Key takeaways\n10. CTA — Engagement driver (question, share request, or resource link)\n\nRules:\n- Each post: max [280 chars for Twitter / 2200 for LinkedIn]\n- Use line breaks for readability\n- Include 1-2 relevant emojis per post (not excessive)\n- Add a "save this 🔖" worthy insight in post #5\n- No hashtag stuffing (max 3 total, only in last post)\n\nTone: [EDUCATIONAL/PROVOCATIVE/INSPIRING]\nConstraints: No engagement bait ("you won\'t believe..."). Every post must standalone while contributing to the narrative.',
    score: 88,
    explanation: 'Platform-specific constraints, sequential narrative structure, engagement psychology, and anti-spam guidelines.',
  },
  {
    id: '17',
    title: 'Unit Test Generator',
    category: 'coding',
    categoryEmoji: '💻',
    prompt: 'You are a QA engineer specializing in test-driven development. Write comprehensive unit tests for the following function/module:\n\n```\n[PASTE CODE]\n```\n\nTesting framework: [JEST/PYTEST/MOCHA/etc.]\n\nTest categories to cover:\n1. **Happy Path** (3-5 tests) — Expected inputs → expected outputs\n2. **Edge Cases** (3-5 tests) — Boundary values, empty inputs, max values\n3. **Error Handling** (2-3 tests) — Invalid inputs, null/undefined, wrong types\n4. **Integration Points** (if applicable) — Mock external dependencies\n\nFor each test:\n- Descriptive test name following "should [expected behavior] when [condition]"\n- Arrange → Act → Assert pattern\n- Comments explaining why this test matters\n\nAlso provide:\n- Test coverage estimate\n- Any testability issues in the original code\n- Suggested refactors to improve testability\n\nConstraints: Tests must be independent (no shared state). Use meaningful test data, not "test123".',
    score: 92,
    explanation: 'Comprehensive test categories, naming conventions, testing patterns, and code quality feedback.',
  },
  {
    id: '18',
    title: 'SWOT Analysis Generator',
    category: 'business',
    categoryEmoji: '📊',
    prompt: 'You are a strategic consultant. Conduct a detailed SWOT analysis for [COMPANY/PRODUCT] in the [INDUSTRY] market for [YEAR].\n\nFor each quadrant, provide 5-7 points:\n\n**Strengths (Internal, Positive)**\n- What advantages does the company have?\n\n**Weaknesses (Internal, Negative)**\n- What could be improved?\n\n**Opportunities (External, Positive)**\n- What trends could be leveraged?\n\n**Threats (External, Negative)**\n- What obstacles exist?\n\nThen provide:\n1. **SO Strategies** (use Strengths to capture Opportunities) — 3 strategies\n2. **WO Strategies** (overcome Weaknesses using Opportunities) — 3 strategies\n3. **ST Strategies** (use Strengths to avoid Threats) — 3 strategies\n4. **WT Strategies** (minimize Weaknesses and avoid Threats) — 3 strategies\n\nFormat: Use a 2x2 table for the SWOT, then numbered strategies.\nConstraints: Be specific to the company. No generic observations. Cite industry trends where possible.',
    score: 90,
    explanation: 'Complete SWOT framework with cross-quadrant strategies, specificity requirements, and structured output format.',
  },
  {
    id: '19',
    title: 'Personalized Study Plan',
    category: 'education',
    categoryEmoji: '🎓',
    prompt: 'You are an academic coach who helps students excel. Create a personalized [DURATION]-week study plan for mastering [SUBJECT/EXAM].\n\nStudent profile:\n- Current level: [BEGINNER/INTERMEDIATE/ADVANCED]\n- Available study time: [HOURS] per week\n- Learning style: [VISUAL/AUDITORY/KINESTHETIC/READING]\n- Weak areas: [LIST]\n- Goal: [TARGET SCORE/OUTCOME]\n\nPlan structure (per week):\n| Day | Topic | Activity | Duration | Resources |\n|-----|-------|----------|----------|----------|\n\nInclude:\n- Progressive difficulty (build on previous weeks)\n- Active recall sessions (practice tests, flashcards)\n- Spaced repetition schedule\n- 1 rest day per week\n- Weekly milestone check-in questions\n- Recommended free resources (YouTube channels, websites, apps)\n\nConstraints: Realistic pacing. Don\'t cram. Include buffer time for review.',
    score: 91,
    explanation: 'Personalized inputs, evidence-based learning techniques (spaced repetition, active recall), structured weekly plans, and realistic pacing.',
  },
  {
    id: '20',
    title: 'Worldbuilding Guide',
    category: 'creative',
    categoryEmoji: '🎨',
    prompt: 'You are a fantasy/sci-fi worldbuilder who has consulted on major franchises. Create a comprehensive world bible for a [GENRE] setting.\n\nCore parameters:\n- Era/Tech Level: [DESCRIPTION]\n- Tone: [DARK/HOPEFUL/MORALLY GRAY]\n- Scale: [SINGLE CITY/CONTINENT/PLANET/GALAXY]\n\nBuild out these layers:\n1. **Geography & Environment** — Key locations, climate, resources\n2. **History** — 3 major historical events that shaped the present\n3. **Political Structure** — Government type, factions, power dynamics\n4. **Culture & Society** — Customs, beliefs, social hierarchy\n5. **Magic/Technology System** — Rules, limitations, costs\n6. **Economy** — Currency, trade, class structure\n7. **Conflict** — Central tensions and unresolved issues\n8. **Unique Element** — One thing that makes this world unlike any other\n\nFor each layer: 1-2 paragraphs + a "story hook" (a conflict or mystery for this layer).\n\nConstraints: Internal consistency is paramount. Flag any potential contradictions. Avoid tropes unless subverted.',
    score: 93,
    explanation: 'Comprehensive worldbuilding layers, internal consistency requirements, story hooks for each element, and trope awareness.',
  },
  {
    id: '21',
    title: 'LinkedIn Post Optimizer',
    category: 'content',
    categoryEmoji: '✍️',
    prompt: 'You are a LinkedIn growth expert whose posts average 50K+ impressions. Rewrite the following post for maximum engagement:\n\n[PASTE ORIGINAL POST]\n\nOptimize for:\n1. **Hook** (first 2 lines) — Must stop the scroll. Use pattern interrupts.\n2. **Structure** — Short paragraphs (1-2 sentences max). Use line breaks.\n3. **Story Arc** — Problem → Insight → Lesson → CTA\n4. **Readability** — Simple words, active voice, conversational tone\n5. **CTA** — End with a question that invites comments\n\nProvide:\n- The optimized post (ready to copy-paste)\n- 3 alternative hook options\n- Best posting time recommendation\n- 3-5 relevant hashtags\n\nConstraints: Under 1,300 characters. No corporate jargon. No humble bragging. Authentic voice.',
    score: 87,
    explanation: 'Platform-specific optimization, engagement psychology, structural requirements, and authenticity constraints.',
  },
  {
    id: '22',
    title: 'Database Schema Designer',
    category: 'coding',
    categoryEmoji: '💻',
    prompt: 'You are a database architect. Design a normalized database schema for [APPLICATION TYPE].\n\nRequirements: [LIST KEY FEATURES]\nExpected scale: [USERS/RECORDS]\nDatabase: [POSTGRESQL/MYSQL/MONGODB]\n\nProvide:\n1. **Entity-Relationship Diagram** (text-based using ASCII or mermaid syntax)\n2. **Table Definitions** — For each table:\n   - Column name, type, constraints\n   - Primary and foreign keys\n   - Indexes (with justification)\n3. **Sample Queries** — 5 common queries the app will need\n4. **Migration Script** — CREATE TABLE statements\n5. **Scaling Considerations** — Partitioning, caching, read replicas\n\nDesign principles:\n- 3NF minimum (denormalize only with justification)\n- UUID primary keys\n- Soft deletes where appropriate\n- Audit columns (created_at, updated_at)\n- Row-level security considerations\n\nConstraints: Optimize for read-heavy workload. Include data validation at the schema level.',
    score: 93,
    explanation: 'Complete database design lifecycle, normalization principles, scaling considerations, and security-aware design.',
  },
  {
    id: '23',
    title: 'Pitch Deck Outline',
    category: 'business',
    categoryEmoji: '📊',
    prompt: 'You are a startup pitch coach who has helped raise $100M+ in funding. Create a 12-slide pitch deck outline for [COMPANY NAME], a [ONE-LINE DESCRIPTION].\n\nSlide-by-slide:\n1. **Title** — Company name, tagline, your name\n2. **Problem** — The pain point (make it visceral)\n3. **Solution** — Your product in one clear sentence + screenshot description\n4. **Demo/How It Works** — 3-step user journey\n5. **Market Size** — TAM, SAM, SOM with sources\n6. **Business Model** — How you make money (pricing table)\n7. **Traction** — Key metrics, growth rate, logos\n8. **Competition** — 2x2 matrix positioning\n9. **Team** — Why YOU can build this\n10. **Financials** — Revenue projections (3 years)\n11. **The Ask** — How much, what for, milestones\n12. **Vision** — The big picture (5-year moonshot)\n\nFor each slide provide:\n- Headline (7 words max)\n- 3-4 bullet points of content\n- Speaker notes (what to say)\n- Design suggestion\n\nConstraints: Investor attention span = 3 minutes. Lead with the strongest metric. No jargon.',
    score: 92,
    explanation: 'Proven pitch structure, investor psychology, specific deliverables per slide, and presentation design guidance.',
  },
  {
    id: '24',
    title: 'Research Paper Summarizer',
    category: 'education',
    categoryEmoji: '🎓',
    prompt: 'You are an academic researcher and science communicator. Summarize the following research paper/article for two audiences:\n\n[PASTE PAPER/ABSTRACT/LINK]\n\n**Summary 1 — For Experts (200 words):**\n- Key findings and methodology\n- Statistical significance and effect sizes\n- Limitations acknowledged\n- How it advances the field\n- Connection to related work\n\n**Summary 2 — For General Audience (200 words):**\n- What problem the researchers studied\n- What they found (in plain English)\n- Why it matters for everyday life\n- One surprising insight\n- Caveats and what we still don\'t know\n\nAlso provide:\n- 5 key terms defined\n- 3 follow-up questions this paper raises\n- Relevance score (1-10) for [FIELD/TOPIC]\n- One-sentence "dinner party" explanation\n\nConstraints: Distinguish between correlation and causation. Note sample size. Flag if findings are preliminary.',
    score: 90,
    explanation: 'Dual-audience approach, scientific rigor requirements, key term definitions, and critical analysis constraints.',
  },
  {
    id: '25',
    title: 'Character Profile Builder',
    category: 'creative',
    categoryEmoji: '🎨',
    prompt: 'You are a character development specialist for novels and screenplays. Create a deep, multi-dimensional character profile.\n\n**Basics:**\n- Name, Age, Occupation: [INPUT]\n- Story role: [PROTAGONIST/ANTAGONIST/MENTOR/etc.]\n- Genre: [INPUT]\n\n**Build these layers:**\n\n1. **External Profile** — Appearance, mannerisms, speech patterns, first impression\n2. **Psychology** — MBTI type, core belief, greatest fear, deepest desire\n3. **Backstory** — 3 defining moments that shaped who they are\n4. **The Wound** — What emotional trauma drives their behavior?\n5. **The Mask** — How they present vs. who they really are\n6. **Relationships** — 3 key relationships and dynamics\n7. **Arc** — Where they start → crisis point → where they end\n8. **Voice** — Write 3 sample dialogue lines that capture their unique voice\n9. **Contradiction** — One trait that seems to contradict their persona\n10. **Symbol** — A recurring motif or object associated with them\n\nConstraints: Avoid stereotypes. The character must feel like a real person with contradictions. No perfect heroes or pure villains.',
    score: 92,
    explanation: 'Comprehensive character development framework, psychological depth, narrative arc integration, and anti-stereotype constraints.',
  },
  {
    id: '26',
    title: 'High-Converting Facebook Ad Specialist',
    category: 'marketing',
    categoryEmoji: '📢',
    prompt: 'You are an elite direct-response copywriter and Facebook Ads specialist with $50M+ in ad spend management. Write 3 distinct Facebook ad copy variations for [PRODUCT/SERVICE] targeting [AUDIENCE].\n\nFor each variation, provide:\n1. **Hook** (first sentence, high psychological pattern interrupt)\n2. **Body Copy** (storytelling or pain-point centric explanation)\n3. **Visual Direction** (image or video storyboard description)\n4. **CTA Button text**\n5. **Headline** (under 40 characters)\n\nStyles to cover:\n- Variation 1: Case Study / Social Proof style\n- Variation 2: Fear-Of-Missing-Out (FOMO) / Urgency style\n- Variation 3: Direct Benefit / Logical argument style\n\nConstraints: Strictly keep post formatting (spacing, bold, emoji) optimized for social scroll-stopping. No high-level corporate jargon.',
    score: 93,
    explanation: 'Uses direct-response copywriting archetypes, provides distinct angles, outlines exact visual assets, and includes formatting rules.'
  },
  {
    id: '27',
    title: 'SaaS Product Launch Email Sequence',
    category: 'marketing',
    categoryEmoji: '📢',
    prompt: 'You are a veteran email marketing automation architect. Design a 3-part product launch email sequence for [PRODUCT] targeting [AUDIENCE].\n\nEmails to include:\n1. **Email 1: The Announcement & Pain Point** (Build excitement, present the problem, introduce product as solution)\n2. **Email 2: Value Deep-Dive & Social Proof** (Highlight top 3 features, explain benefits, add mock testimonial placeholder)\n3. **Email 3: The Pitch & Urgency** (Clear offer, FAQ section, final call-to-action, time-sensitive incentive)\n\nFor each email, provide:\n- Subject Line (with 2 alternative options)\n- Preheader Text\n- Complete body copy with clear placeholders (e.g. [First Name], [Price])\n- Recommended click trigger links\n\nTone: Friendly, urgent, and educational.',
    score: 91,
    explanation: 'Sequenced structure, comprehensive deliverables, variable placeholders, and targeted email mechanics.'
  },
  {
    id: '28',
    title: 'Strict Coding System Directive',
    category: 'system',
    categoryEmoji: '⚙️',
    prompt: 'You are a strict system interpreter for a clean-architecture React/TypeScript project. Your responses must contain ONLY valid React/TypeScript code and absolutely no Markdown explanation or chat dialogue.\n\nContext: We are building an enterprise dashboard using Tailwind CSS.\n\nRules:\n- Never output a paragraph, greeting, or signoff.\n- If you must include comments, insert them strictly as standard JS inline comments (//) inside the code block.\n- Format imports using clean ESM imports.\n- Adhere to functional programming styles and strict types.\n\nCode request: [INSERT TASK]',
    score: 95,
    explanation: 'Implements absolute negative constraints (no explanation), sets structural workspace environment parameters, and specifies strict code validation rules.'
  },
  {
    id: '29',
    title: 'Recursive Meta-Prompt Constructor',
    category: 'system',
    categoryEmoji: '⚙️',
    prompt: 'You are an advanced meta-prompting engineer. Your task is to take a basic user prompt and reconstruct it into an elite, high-scoring prompt using the PromptGrade Blueprint framework.\n\nUser Input Prompt: "[PASTE PROMPT]"\n\nRefactor the prompt by dynamically compiling these sections:\n1. **Expert Role Assignment** (who is the model?)\n2. **Target Context & Parameters** (situation parameters)\n3. **Step-by-Step Instructions** (clear workflow execution)\n4. **Structured Format Specifications** (explicit output layouts)\n5. **Rigid Constraints & Guardrails** (what is strictly banned?)\n\nProvide only the final copyable prompt wrapped inside a clean markdown block.',
    score: 94,
    explanation: 'Applies recursive prompt building logic, targeting the PromptGrade framework directly to produce a robust system prompt.'
  },
  {
    id: '30',
    title: 'Advisory Board Simulation System',
    category: 'system',
    categoryEmoji: '⚙️',
    prompt: 'You are acting as an Advisory Board consisting of three expert personas: a Chief Executive Officer (CEO), a Principal Software Architect (CTO), and a Lead Product Designer (CPO). Simulating a group roundtable, discuss the following proposal: "[INSERT PROPOSAL]".\n\nFor each round of discussion, output:\n- **[CTO Review]**: Technical feasibility, scalability risks, and schema choices.\n- **[CPO Review]**: User friction points, experience quality, and journey simplicity.\n- **[CEO Verdict]**: Strategic business viability, resource efficiency, and ROI analysis.\n\nFinally, deliver a consolidated "Action Plan Consensus" signed by all three board members.',
    score: 93,
    explanation: 'Leverages multi-persona cooperative roundtables, reducing biased outputs and providing comprehensive, multi-dimensional business evaluations.'
  }
];
